import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {DatabaseSync} from 'node:sqlite';
test('HTTP sessions, score tampering, origin checks, and persistence',async t=>{
  const dir=await mkdtemp(path.join(tmpdir(),'isles-test-'));const root=fileURLToPath(new URL('../',import.meta.url));
  const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PORT:'5194',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{child.kill();await new Promise(r=>child.once('exit',r));await rm(dir,{recursive:true,force:true});});
  await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',c=>reject(Error(`server exit ${c}`)));});
  const base='http://127.0.0.1:5194';let response=await fetch(base+'/api/state');const cookie=response.headers.get('set-cookie').split(';')[0];let state=await response.json();assert.equal(state.player.salvage,0);assert.equal(state.leaderboard.length,0);
  const post=(route,data,extra={})=>fetch(base+'/api/'+route,{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json',...extra},body:JSON.stringify(data)});
  response=await post('profile',{name:'Test Voyager'});assert.equal((await response.json()).player.name,'Test Voyager');
  response=await post('profile',{name:'<script>'});assert.equal(response.status,400);
  response=await post('start',{});const run=(await response.json()).run;assert.equal(run.status,'active');
  response=await post('start',{});assert.equal((await response.json()).run.id,run.id);
  response=await post('input',{score:999999,salvage:999999,hp:999999,x:1910,y:560,bossDead:true});const s=(await response.json()).run;assert.equal(s.score,0);assert.equal(s.salvage,0);assert.equal(s.player.hp,120);assert.equal(s.bossDead,false);
  response=await post('relic',{relic:'storm'});assert.equal(response.status,400);
  response=await post('contribute',{amount:50});assert.equal(response.status,400);
  response=await post('contribute',{amount:-50});assert.equal(response.status,400);
  response=await post('profile',{name:'Attacker'},{Origin:'https://evil.example'});assert.equal(response.status,403);
  response=await post('leave',{});assert.equal(response.status,200);
  response=await fetch(base+'/api/state',{headers:{Cookie:cookie}});state=await response.json();assert.equal(state.player.name,'Test Voyager');assert.equal(state.player.best,0);assert.equal(state.player.salvage,0);assert.equal(state.run.status,'abandoned');
  response=await fetch(base+'/server.js');assert.equal(response.status,404);
  response=await post('shop/buy',{item:'axe',cost:0});assert.equal(response.status,400);
  response=await post('weapon/equip',{weapon:'spear'});assert.equal(response.status,200);assert.equal((await response.json()).player.gear.weapon,'spear');
  response=await post('weapon/equip',{weapon:'admin'});assert.equal(response.status,400);
  const fixture=new DatabaseSync(path.join(dir,'isles.sqlite'));
  fixture.prepare('UPDATE players SET salvage=100 WHERE id=?').run(state.player.id);fixture.close();
  response=await post('shop/buy',{item:'axe',cost:0});let purchased=await response.json();assert.equal(purchased.player.salvage,40);assert.equal(purchased.player.gear.axe,1);
  response=await post('shop/buy',{item:'axe',cost:0});assert.equal(response.status,400);

  for(const route of ['auth/challenge','auth/verify','arrival/challenge','arrival/verify'])assert.equal((await post(route,{})).status,410);
  const {key}=await (await post('save/key',{})).json();assert.match(key,/^SW-[0-9a-f]{64}$/);
  const fresh=await fetch(base+'/api/state'),freshCookie=fresh.headers.get('set-cookie').split(';')[0];assert.notEqual((await fresh.json()).player.id,state.player.id);
  response=await post('save/restore',{key:'SW-'+'0'.repeat(64)},{Cookie:freshCookie});assert.equal(response.status,401);
  response=await post('save/restore',{key},{Cookie:freshCookie});assert.equal(response.status,200);const restored=await response.json();assert.equal(restored.player.id,state.player.id);assert.equal(restored.player.gear.axe,1);assert.equal(restored.player.salvage,40);
  const recoveredCookie=response.headers.get('set-cookie').split(';')[0];assert.match(response.headers.get('set-cookie'),/Max-Age=31536000/);
  response=await fetch(base+'/api/state',{headers:{Cookie:recoveredCookie}});assert.equal((await response.json()).player.name,'Test Voyager');
});
